version: '3'
services:
  FrontEnd:
    build: ./Frontend
    image: maxiaolin/seba_find_my_cook_front_end:latest
    container_name: seba_find_my_cook_front_end
    command: npm start
    depends_on:
      - BackEnd
    ports:
      - "8081:8081"
    volumes:
    - '.:/usr/src/Frontend'
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/:/data/db
    ports:
        - "27017:27017"
  BackEnd:
    build: ./Backend
    image: maxiaolin/seba_find_my_cook_back_end:latest
    container_name: seba_find_my_cook_back_end
    ports:
        - "3000:3000"
    depends_on:
        - mongodb
    environment:
        - mongodb_uri=mongodb://mongodb:27017/findmycook
networks:
  webappnetwork:
    driver: bridge